#syntax=docker/dockerfile:1
FROM debian:bookworm
RUN mkdir /app
COPY ./%DEB_FILE% /app
RUN apt-get update && \
    apt-get install -y /app/%DEB_FILE% && \
    rm /app/%DEB_FILE% && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

CMD ["/usr/share/epikur4Server/bin/start.sh"]

